=== SIrRob525/Labs/Lab2/scheme.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:complexType name="Session">
    <xs:all>
        <xs:element name="subject" type="xs:string"/>
        <xs:element name="classroom" type="xs:string"/>
        <xs:element name="instructor" type="xs:string"/>
        <xs:element name="start" type="xs:time"/>
        <xs:element name="end" type="xs:time"/>
        <xs:element name="type">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="lecture"/>
                    <xs:enumeration value="seminar"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:element>
    </xs:all>
    <xs:attribute name="day" use="required">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="mon|tue|wed|thu|fri|sat|sun"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
</xs:complexType>


<xs:element name="timetable">
    <xs:complexType>
        <xs:choice maxOccurs="unbounded">
            <xs:element name="session" type="Session"/>
        </xs:choice>
    </xs:complexType>   
</xs:element>


</xs:schema>

=== SIrRob525/Labs/Lab2/timetable.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="file:///C:/Users/ibori/Desktop/Homeworks/sem3/internet_data_analysys/Lab2/totext.xslt"?>

<!--!DOCTYPE timetable SYSTEM "C:\Users\ibori\Desktop\Homeworks\sem3\internet_data_analysys\Lab2\scheme.dtd"-->

<timetable 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation=
"C:\Users\ibori\Desktop\Homeworks\sem3\internet_data_analysys\Lab2\scheme.xsd">

    <session day="mon">
        <subject>Микроэкономика-2</subject>
        <classroom>341</classroom>
        <instructor>А. Кальчевский</instructor>
        <start>12:30:00</start>
        <end>13:50:00</end>
        <type>seminar</type>
    </session>

    <session day="tue">
        <subject>Макроэкономика-1</subject>
        <classroom>R503</classroom>
        <instructor>В. Черноокий</instructor>
        <start>13:00:00</start>
        <end>14:20:00</end>
        <type>lecture</type>
    </session>

    <session day="tue">
        <subject>Машинное обучение</subject>
        <classroom>R205</classroom>
        <instructor>М. Гущин</instructor>
        <start>16:20:00</start>
        <end>17:40:00</end>
        <type>lecture</type>
    </session>

    <session day="wed">
        <subject>Математический анализ-2</subject>
        <classroom>R503</classroom>
        <instructor>С. Шапошников</instructor>
        <start>09:30:00</start>
        <end>10:50:00</end>
        <type>lecture</type>
    </session>

    <session day="wed">
        <subject>Математический анализ-2</subject>
        <classroom>G119</classroom>
        <instructor>Т. Красовицкий</instructor>
        <start>13:00:00</start>
        <end>14:20:00</end>
        <type>seminar</type>
    </session>

    <session day="wed">
        <subject>Макроэкономика-1</subject>
        <classroom>R504</classroom>
        <instructor>В. Черноокий</instructor>
        <start>11:10:00</start>
        <end>12:30:00</end>
        <type>lecture</type>
    </session>

    <session day="wed">
        <subject>Машинное обучение</subject>
        <classroom>R506</classroom>
        <instructor>В. Бочарников</instructor>
        <start>14:40:00</start>
        <end>16:00:00</end>
        <type>lecture</type>
    </session>

    <session day="fri">
        <subject>Математический анализ-2</subject>
        <classroom>R503</classroom>
        <instructor>С. Шапошников</instructor>
        <start>09:30:00</start>
        <end>10:50:00</end>
        <type>lecture</type>
    </session>

    <session day="fri">
        <subject>Микроэкономика-2</subject>
        <classroom>R504</classroom>
        <instructor>О. Баранов</instructor>
        <start>11:10:00</start>
        <end>12:30:00</end>
        <type>lecture</type>
    </session>

    <session day="fri">
        <subject>Технологии анализа данных в сети Интернет</subject>
        <classroom>online</classroom>
        <instructor>В. Ланин</instructor>
        <start>13:00:00</start>
        <end>14:20:00</end>
        <type>lecture</type>
    </session>
    
    <session day="fri">
        <subject>Технологии анализа данных в сети Интернет</subject>
        <classroom>online</classroom>
        <instructor>В. Ланин</instructor>
        <start>14:40:00</start>
        <end>16:00:00</end>
        <type>seminar</type>
    </session>
    
    <session day="fri">
        <subject>Микроэкономика-2</subject>
        <classroom>S224</classroom>
        <instructor>А. Кальчевский</instructor>
        <start>16:20:00</start>
        <end>17:40:00</end>
        <type>seminar</type>
    </session>

    <session day="sat">
        <subject>Машинное обучение</subject>
        <classroom>R307</classroom>
        <instructor>С. Корпачев</instructor>
        <start>14:40:00</start>
        <end>16:00:00</end>
        <type>seminar</type>
    </session>

</timetable>
